### ISSUE TITLE
Relevance of mortality data?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#10]
The line numbers referenced by the reviewer don't match up with what they're talking about, so it's unclear exactly what they're talking about here.

>Line 204-207: These data are mentioned in the discussion but it’s unclear from the introduction as to why these experiments were done in the first place. What direct relevance does this have on the rest of the data and or with respect to how this work falls within the greater body of the literature?

**Comment by sr320** [comment]
See 
![img_0240](https://cloud.githubusercontent.com/assets/4442039/25400117/6f451c62-29a6-11e7-9f54-0bb512e3df0f.PNG)

**Comment by sr320** [comment]
Mortality data was included to provide a greater context of organismal state as physiological stress approaching death would be relavant for interpreation of gene expression data.

**Comment by kubu4** [comment]
Both reviewers have qualms with the mortality information. 

I'll put in a vote to just ditch the mortality-related aspects of the paper entirely.

If we opt to leave it in, we have a fair amount of work to do:

- Perform, and show, statistical analysis to support our claims of no statistical differences between population survival
- Explain differences in survivorship between our study and other studies referred to in the paper
- Clarify why mortality was assessed, and how mortality relates to the gene(s) and expression that were measured.

**Comment by sr320** [comment]
Go ahead and ditch
