### ISSUE TITLE
Box plots don't show all data points

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#2]
Large outlier values aren't displayed on the plots. Modifying the plots to accommodate these outliers compresses the plots too much. What're the thoughts on this? Was this discussed when the plots were initially generated?

**Comment by sr320** [comment]
Is this based on a specific comment of reviewers? I presume outliers were used in calculating boxes?

**Comment by kubu4** [comment]
Not based on reviews. I noticed it when re-running the R script that generate the plots (error messages are generated).

The outlier data is used in the box plot calculations, but is not displayed on the plots due to the limitations of the y-axis scale.

**Comment by sr320** [comment]
Then we should just indicate outliers not shown, and data is provided.

**Comment by kubu4** [comment]
Well, it's a subset of outliers that aren't shown...

**Comment by kubu4** [comment]
So, could we say a subset of outliers is not shown to improve plot readability?

**Comment by sr320** [comment]
Sound good, could actually indicate number of outliers in each set not shown
