### ISSUE TITLE
Version reviewers read?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/paper-Olurida-gene#21]
I would assume reviewers would have read 
https://peerj.com/preprints/1595/

but the numbers line numbers they refer to do not jive. 

Specifically I cannot find "Data not Shown" in lines 149 and 207

What version did they get?

**Comment by grace-ac** [comment]
They got the correct version but when word doc was changed to pdf or vice
versa, the line numbers changed.

So when I added the reviewer comments to the word doc, I looked at the PDF
that they had with the line numbers, and then matched that text to the line
numbers in the word doc.

**Comment by sr320** [comment]
But 
https://peerj.com/preprints/1595/

does not have "Data not Shown" anywhere in the paper

So where is PDF they had?

**Comment by kubu4** [comment]
See the end of Issue #1 .

Here's link directly to Reviewer 2's annotated PDF version of what we submitted: https://github.com/RobertsLab/paper-Olurida-gene/blob/master/review-1-137321.pdf

**Comment by sr320** [comment]
Thanks

@grace-ac was actually confused about what Oly paper this was ;)

**Comment by kubu4** [comment]
Not sure how that could happen! ;)
