### ISSUE TITLE
Changes needed

### ISSUE THREAD

**Issue by sr320** [RobertsLab/paper-Olurida-gene#22]
- [x] **Figure/Table Citation**
The first citation for Table 2 (line 183) seems to appear before the first citation for Table 1 (line 327). Citations must be organized, and cited for the first time, in ascending numerical order, meaning Table 1 must always be cited first, Table 2 must always be cited second, and so on. Please edit the citations in your manuscript and re-upload the document here <https://peerj.com/manuscripts/12793/files/>.

- [x] **Figure Permissions** 
Could you please confirm that Figure 1 is not copyrighted, or if it is, you have permission to publish it under our CC BY 4.0 license? Please leave a note to staff at <https://peerj.com/manuscripts/12793/declarations/#other>. If it is taken from copyrighted material, we will need a copy of the written permission for our records uploaded as a Supplemental File here: <https://peerj.com/manuscripts/12793/files/>. A sample permission letter can be found here: <https://peerj.com/about/author-instructions/#figure-referencing>

- [x] **Figure Style** 
For maximum reader accessibility, please remove the patterns/gradients in Figure 1.

- [x] **Authorship** 
Brent Vadopalas still needs to confirm their co-authorship using the email they received from PeerJ. Please ask them to check their spam folders.

If they did not receive the confirmation email or if you entered the wrong email address for them, then edit their information at <https://peerj.com/manuscripts/12793/authors/coauthors/> and 'resend' the email to them.

NOTE: If your submission is accepted for publication and your co-authors have not confirmed authorship it will cause delays.

- [x] **Additional Author** 
We noticed that this revised version now includes an additional author Brent Vadopalas. As PeerJ adheres to the ICMJE uniform requirements of authorship (<http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html#two>), could you please explain why this additional author was added at the revision stage.

1) Send an email to editorial.support@peerj.com to clarify this change, and justify their inclusion by indicating their specific contribution in relation to the original work.

2) In addition to explaining the change in authorship, all co-authors need to be informed of this change (and to be given the opportunity to comment if needed). Please send an email to all co-authors informing them of this change in authorship and cc: editorial.support@peerj.com. Please let the co-authors know that they must reply to the email directly to me at editorialsupport@peerj.com, not reply all to the email you sent, to confirm they agree with the addition.

**Comment by kubu4** [comment]
Checked off Fig Permissions & Authorship above.

**Comment by kubu4** [comment]
Checked off Figure/Table Citation above.

Added Table 1 citation. Saved as version v28.

**Comment by kubu4** [comment]
Checked off Figure Style above.

Removed map, per @sr320's instructions here: https://github.com/RobertsLab/resources/issues/131#issuecomment-345773012

Updated all remaining figure numbering in manuscript. Saved as v29.

**Comment by kubu4** [comment]
Also updated figure .eps files in Dropbox folder.

**Comment by kubu4** [comment]
Uploaded v29 of manuscript to PeerJ.

**Comment by kubu4** [comment]
Checked off Additional Author above.

Reported as completed here: https://github.com/RobertsLab/resources/issues/131#issuecomment-347572528
