### ISSUE TITLE
qPCR "raw" data missing (i.e. data from tech reps)

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#3]
The data set currently starts from a spreadsheet that contains just mean Ct values. Do we need/want a spreadsheet with all replicates from all samples?

**Comment by kubu4** [comment]
Jake mentions that @sr320 has some sort of master sheet? 

http://heareresearch.blogspot.com/2015/09/9-1-2015-mean-ct-value-stats-and-graphs.html

**Comment by sr320** [comment]
this is a response to specific reviewers comment?
Related it might make sense to have each comment an "issue"

**Comment by kubu4** [comment]
Yes. Relates to question regarding replicates.

We have this fancy R script to replicate figures, but we start with mean Ct/Cq values and no information provided regarding the raw data, nor any assessment/statement about consistency between replicates.

We could just make a statement regarding this (e.g. Mean Ct/Cq values were determined from qPCR technical replicates (n=tech_reps) for each sample.).

**Comment by kubu4** [comment]
Not providing "raw" data in manuscript.
