### ISSUE TITLE
Clarification of gene function determination and selection process

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#4]
>This table is useful, but please comment on how gene function was inferred from sequence. Is this from GO terms based on closest known homolog? Is this manual or semi-automated curation? Additionally, are there potential paralogues for these genes and why was one picked over another? The authors even suggest that the HSP70 transcript they chose may not actually be the true HSP70-like protein in other organisms given the lack of transcript change in response to heat stress.

**Comment by sr320** [comment]
![img_0239](https://cloud.githubusercontent.com/assets/4442039/25399426/43e62784-29a4-11e7-9ea5-b72c31236841.PNG)

**Comment by sr320** [comment]
Gene function is based on the protein in the UniProt/SwissProt database that had highest homologous with the Olympia oyster sequence, in other words the top blast hit.  It is possible there are paralogs in the data, though we would not be able to determine if contigs were different genes or different region of same gene. Considerations taken to select genes include function of top blastsx hit, evalue, and diversity in general physiological process.

**Comment by kubu4** [comment]
Added to <em>Primer Design</em> subsection of MATERIALS AND METHODS.
