### ISSUE TITLE
Add gene categorizations to Table 1

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#5]

**Comment by sr320** [comment]
Specific comment from reviewer?

**Comment by kubu4** [comment]
Yes.

**Comment by sr320** [comment]
thors state “A suite of genes was selected based on their predicted
function (gene regulation, immune response, and growth).” Binning the genes
in to these categories in the table helps connect the experimental design
to the hypothesis and may make discussion of the results easier.

**Comment by kubu4** [comment]
- [x] Split table into two: 1. Gene targets/descriptions. 2. Genes and primers
- [x] Change Uniprot ID to accession
- [x] Change CRAF to TRAF (needs to be fixed throughout paper)
