### ISSUE TITLE
Need info on DNased RNA gDNA qPCR

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#6]
>Please comment on which primers were used to detect genomic DNA via PCR. Were primers targeted to intronic or mRNA non-coding regions? Or were primers generating an amplicon spanning an exon junction used?

**Comment by sr320** [comment]
I would say actin was used on treated RNA? And no amplification indicated no genomic DNA? We would need some control though to make sure it would in fact have amplified genomic. 
Maybe we used a different gene we knew intron structure of?

**Comment by kubu4** [comment]
Added following sentence to paper: 

>Treated RNA was verified to be free of gDNA via qPCR using actin primers (see Quantitative PCR section below) known to amplify gDNA.
