### ISSUE TITLE
Clarify tissue handling

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#7]
>Would the authors please clarify if tissue was pooled from animals. Explicit descriptions of what one data point represents would assist with interpretation of data and assessment of its robustness. Further, were technical replicates performed, or was only one RT-qPCR reaction performed per unique animal per gene?

**Comment by sr320** [comment]
Include graph? / context of "data point"

**Comment by kubu4** [comment]
I think some sentences are fine, although a figure that lays out the experimental design would be nice.

**Comment by sr320** [comment]
No that question was for you :) what is the comment referring to - a graph?

**Comment by kubu4** [comment]
Oh! Ha!

I was just putting up reviewer comments in the Issues of this repo, as proposed in Issue #3 .

So, this issue doesn't really require any feedback (as I'll close it out once it's addressed in the manuscript), but, in retrospect, I still think adding a figure outlining the experimental design would be good.

**Comment by kubu4** [comment]
Clarified this in paper with the following two sections:
#### Experimental Design
>Oysters from each population (n=8 per population) were subjected to acute temperature stress (submerged in 500mL 38°C sea water for 1 hour), mechanical stress (1000 rpm x 5 min; Sorvall T21, ST-H750 rotor) or served as controls (maintained at 8°C). After the stress treatments, oysters were returned to 8°C seawater and sampled at 1 hour post stress (n=72). Ctenidia tissue was dissected from each individual and stored stored separately in 500μL RNAzol RT (Molecular Research Center, Inc.) at -80°C for later analysis.

#### Quantitative PCR

>Two qPCR replicates were run for each sample, for each primer set.
