### ISSUE TITLE
Explain/clarify qPCR analysis

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#8]
>Please explicitly state why the normalized mRNA levels are calculated as ΔCt= (target Ct – actin Ct) as well as why a logΔCt were used for statistical analysis. In the results section the y-axis is labeled as the data being plotted at a ΔCt value. The statistical calculations being performed on logΔCt value but the graphs showing just the ΔCt can be a bit confusing. It’s not so much that there’s an inherent problem with how the data were analyzed, but rather just being clear why it was done this way.

**Comment by sr320** [comment]
Confer with Brent - but my recall is log was used to better meet assumptions of stat test...
Normalization

**Comment by kubu4** [comment]
Updated text and revised to reflect use of logΔCt throughout. Figures need updating - created separate issue #12 .
