### ISSUE TITLE
Presence of SNPs in priming sites

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#9]
>Please comment on whether the priming sites for the primers were known to contain SNPs that may have affected hybridization efficiency. This should be available since the Authors’ lab appears to have made its own transcriptome and have access to raw sequencing reads.

**Comment by sr320** [comment]
FFS

**Comment by sr320** [comment]
Priming sites are not known to have SNPs. The transcriptome was generated from a different population of oysters thus would not be directly informative. We cannot completely exclude the possibility of SNPs in the oysters examined. This could be determined with targeted high-throughput sequencing or targeted Sanger sequencing, both beyond the scope of this work.

**Comment by kubu4** [comment]
I need to read a bit more, but is it possible this was actually checked this out via Sanger sequencing already??

http://heareresearch.blogspot.com/2015/06/6-23-2015-flanking-primer-pcr-pt-3.html

http://onsnetwork.org/kubu4/2015/06/25/sample-submission-olympia-oyster-pcrs-sanger-sequencing-2/

**Comment by kubu4** [comment]
I've added the following section to address impact of SNPs in primer binding sites, but I'm not sure if this requires supporting data or not: 

>Primer binding sites were assessed for the presence of single nucleotide polymorphisms (SNPs) via Sanger sequencing. The majority of primer binding sites did not contain any SNPs. Those that did had only a single SNP and did not appear to impact qPCR data, as there was no noticeable difference in qPCR efficiencies in individuals having a SNP within a primer binding site for a given target.

**Comment by kubu4** [comment]
Change to say something about Sanger sequencing of subset of primer binding sites.
